﻿info:
  description: main config file
eureka:
  instance:
    preferIpAddress: true
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启Spring Cloud的重试功能
 #日志级别
logging:
  level:
    com.leyou: debug
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
############################################################################################
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    #    lk-user-server: # 这里是路由id，随意写
    #      path: /user-server/** # 这里是映射路径
    #      service-id: lk-user-server # 指定服务名称
    lk-user-server: /user/** # 这里是映射路径
# ignored-services:
#   - upload-service # 忽略upload-service服务
#   add-host-header: true #携带请求本身的head头信息
#   sensitive-headers: #匹配禁止使用的头信息，这里设置为null，否则set-cookie无效
############################################################################################
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka/,http://127.0.0.1:10087/eureka/
    registry-fetch-interval-seconds: 5
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/lk
    username: root
    password: 1qaz@k
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10